//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weebul.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fighter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fighter()
        {
            this.Fights1 = new HashSet<Fight>();
            this.Fights2 = new HashSet<Fight>();
        }
    
        public int FighterId { get; set; }
        public string Name { get; set; }
        public int Strength { get; set; }
        public int KOPunch { get; set; }
        public int Speed { get; set; }
        public int Agility { get; set; }
        public int Chin { get; set; }
        public int Conditioning { get; set; }
        public int CutResistance { get; set; }
        public int Height { get; set; }
        public int Build { get; set; }
        public int Weight { get; set; }
        public int Fights { get; set; }
        public int Rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fight> Fights1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fight> Fights2 { get; set; }
    }
}
