//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weebul.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fight()
        {
            this.Rounds = new HashSet<Round>();
        }
    
        public int FightId { get; set; }
        public System.DateTime Date { get; set; }
        public int Fighter1Id { get; set; }
        public int Fighter2Id { get; set; }
        public int Fighter1Score { get; set; }
        public int Fighter2Score { get; set; }
        public Nullable<bool> Fighter1Win { get; set; }
        public int ResultType { get; set; }
        public bool IsParsed { get; set; }
        public int Fighter1PlanId { get; set; }
        public int Fighter2PlanId { get; set; }
        public int OptionsId { get; set; }
        public int NumberOfRounds { get; set; }
        public string ParseText { get; set; }
        public bool BadResult { get; set; }
        public string TkoCut { get; set; }
        public int CutLevelF1 { get; set; }
        public int CutLevelF2 { get; set; }
    
        public virtual Fighter Fighter1 { get; set; }
        public virtual Fighter Fighter2 { get; set; }
        public virtual FightOption FightOption { get; set; }
        public virtual FightPlan FightPlan1 { get; set; }
        public virtual FightPlan FightPlan2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Round> Rounds { get; set; }
    }
}
