//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weebul.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FighterRound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FighterRound()
        {
            this.FighterRoundCuts = new HashSet<FighterRoundCut>();
        }
    
        public int FRID { get; set; }
        public bool IsFighter1 { get; set; }
        public int RoundId { get; set; }
        public double Endurance_Start { get; set; }
        public double Endurance_Damage { get; set; }
        public double Stun_Damage { get; set; }
        public double Base_Damage { get; set; }
        public double Cut_Damage { get; set; }
        public double Fatigue_Start { get; set; }
        public double Fatigue_End { get; set; }
        public int TacticsId { get; set; }
        public bool IsWarned { get; set; }
        public int PowerPunchesLanded { get; set; }
        public int RightsLanded { get; set; }
        public int JabsLanded { get; set; }
    
        public virtual Round Round { get; set; }
        public virtual Tactic Tactic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FighterRoundCut> FighterRoundCuts { get; set; }
    }
}
