//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weebul.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Round()
        {
            this.FighterRounds = new HashSet<FighterRound>();
            this.JudgeRounds = new HashSet<JudgeRound>();
        }
    
        public int RoundId { get; set; }
        public int FightId { get; set; }
        public int Fighter1Score { get; set; }
        public int Fighter2Score { get; set; }
        public int ResultType { get; set; }
        public int RoundNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FighterRound> FighterRounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JudgeRound> JudgeRounds { get; set; }
        public virtual Fight Fight { get; set; }
    }
}
