//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weebul.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tactic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tactic()
        {
            this.FighterRounds = new HashSet<FighterRound>();
        }
    
        public int TacticsId { get; set; }
        public double Aggressiveness { get; set; }
        public double Power { get; set; }
        public double Defense { get; set; }
        public double Rest { get; set; }
        public int Strategy { get; set; }
        public int Target { get; set; }
        public bool Dirty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FighterRound> FighterRounds { get; set; }
    }
}
